### ISSUE TITLE
Z  at the end of instantiation dates and times

### ISSUE THREAD

**Issue by klipska** [cavpp/cavppers#52]
A Z is appearing at the end of the date and time data in the instantiations

` <instantiationDate dateType="recorded">1977Z</instantiationDate>
        <instantiationDate dateType="file modification">2017-08-28T13:23:58Z</instantiationDate>
        <instantiationDate dateType="encoded">2017-08-21T07:31:34Z</instantiationDate>`

**Comment by dericed** [comment]
This is part of ISO8601, see https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC). Do you prefer a different expression for timezone?

**Comment by klipska** [comment]
Ah. Ok, the Z can stay for time zone. 
What about the date though? Does the recorded year need a  Z? "1977Z"

**Comment by dericed** [comment]
This was actually a mediainfolib issue, fixed in https://github.com/MediaArea/MediaInfoLib/pull/927/files.

**Comment by klipska** [comment]
Z is still showing up after dates. See caolaam_000144: `<instantiationDate dateType="recorded">1977Z</instantiationDate>`

Also I found in our vendor pbcore times use "UTC" and have spaces in between the dates and times that make these values more readable. Can we have pbcorethat do it this way? Instead of `<instantiationDate dateType="file modification">2017-08-28T13:30:54Z</instantiationDate>` do `<instantiationDate dateType="file modification">UTC 2017-08-28 13:30:54</instantiationDate>` ?

**Comment by dericed** [comment]
This would require either waiting for and installing the next mediainfo release or perhaps `brew reinstall mediainfo --HEAD` in order to get the latest update of mediainfo.

**Comment by klipska** [comment]
Ok I think we can wait for the MediaInfo updates to remove the Z from dates. 

Let me know about using UTC for the timestamps.

**Comment by dericed** [comment]
Please verify, this appears to be fixed in at least MediaInfoLib - v18.08.1.

**Comment by klipska** [comment]
Z no longer appearing after dates
